language: rust
cache: cargo

rust:
- stable

matrix:
  fast_finish: true      
  include:
  - os: osx
    env: TARGET=x86_64-apple-darwin
  - os: linux
    env: TARGET=x86_64-unknown-linux-musl   

branches:
  only:
  - master

install: ./ci/install.sh      

script: ./ci/script.sh

before_deploy: ./ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
    secure: k7Qt/VHSrEUeEo3A7+Chu3Oy1Ft5JCUyKDNIEgMA2Uz1cxSNLOBN9VH2cSGaTW01G5sMhESG2X0AaPn23cnJgy/XyXcGMs1mfWUE5/ilyhhB+Uw0w16HfHyfjTsDzwh5BnNqrmc6OjEnilLPsz0EkGe8Y9u1DP4+9iHGu6UV/rs/ZC+BJEqvWfHi+1gxVk/oF9aPVgWCviV1nKLbqtVXwVkVDpsEDNmiyHO7QFUZvwwDLL4FzcHMUaGtGKxFK+KS6JGlcUwg+/+CTpxYGpm5rXMkMCNJgIIWg+BvODvM25dpBbohEfTbOGA0ToAkFZP5XgX2E8nI/ymD/BZib8cvn0wche00+SeDVfPtQLPc6MvYiquX92ofvVz7Y68i6BJK10tZG7LzRKELuKqIdvUkUWP3S3tGyfBZNi7o7G++FcCSs3O6uGXkF/JpA1amMzpqdcHgxp+LZ5IGUtesdmOm7VIYEgpJQBzbbQxBJXIgrBm+zwHA4SpcQxrHb/XznCbQyAiTg8n4DCzyNbwIhzHOQIZqVqDSCC/Q4R25oNO08d+uJUaEFeHMXdBsEWYHQneWfkPZZQuAdx+3WH0CMkVEWnrRwsPTJ7LWOePfSLKnYhx14eg8v1ZYYioctYyxZWgQY3i+/qFlgcA6Y8ewDAVtvorHFMaBS/+Ol+J2d/xjfl8=
  file: sdoc-${TRAVIS_TAG}-${TARGET}.tar.gz
  skip_cleanup: true
  on:
    repo: matthewwoodruff/sdoc
    tags: true
