language: rust
cache: cargo
rust:
- stable
- nightly
matrix:
  fast_finish: true
  allow_failures:
  - rust: nightly
  include:
  - os: osx
    env: TARGET=x86_64-apple-darwin
  - os: linux
    env: 
    - TARGET=x86_64-unknown-linux-gnu CARGO_RELEASE=true
    - secure: "QGSRGvIqi28+p8HsvF31fLCgWbruikFq41bR/ILVjKhfdkpc40tkJVd7ausxWcF2r0BBRorqWdiIgCeWrPYAC6iKGr9dleuADZZ1cJxNDI8nI89q1X0Qzl2iU23IGIYrjK+KKtVtWd9JbtG/E3W1aXzw2Km6Gw3Wnlgcp5VD59HNNJ2W41mdP5gdoXEYMwBb2CGKw9C/50kKUdyquB2YLjTcqW6LhiuilS+HTPXvr50DPZuIMl6L9DF0kZD0VMblOr6cN21xdt/DRA7aglan9K26UhVkVKNK4PtbixeSc2c7/Mc7w9H8x3pw66TxpyPnBbVMUz+0gad76rfT+s/gGxKRLO6rW5H7hCkmElfk7O/ON8YZcjKkBQVsM8qrqKvp4vB9ywDRvwm34GFNpgY/yGCaqmKujtUyhXrYiCRYxwljwwXZfFETgxjfDP4RzLdPkZ7Ol0DOyWUqFHFxz003awRokYyt6TrT3biBJzi6jIEnOa4qjuqY7rjKRJv8Og+4CnQU4q8P71Jcz2EEHKBE7BvFayrSI+XJQmPsSUVDuRtpbLmdl0B8N6PE+H3rCn8Q+dKFRVvhuKB7ZeF/9X4wxCzKwt57ioUxn2S1Jdoxs8I0MJ+2Rt34/f1p7xeW6Sp+hyXv2VcJeiP0UhnCKTQNUT8BijTE1fscU5oozldT8fY="
#  - os: linux
#    env: TARGET=x86_64-unknown-linux-musl
script: make build
deploy:
- provider: releases
  api_key:
    secure: "JBdhuIRxaAordv2aAVXOfxdhhSz47KcJvTqqgXA+VAnRRwOIkrxkgVMg0WrQFcg5HbuXfHiwYBaYtgpILUHmN05lnlH8iSv7tfA25dIOcFMDaxWPpnXvlfBLasaskxZc+OwMyZcKeNw05He/8rRQIWjsAffNGUHdnbVsHuVXyStElOWCwp9cpuSel9FYTanlDWV3HgtoCLmoFClxIAwnBfhIaJaMrhcGEAqH1tjNNuq4dY9Rv01WAEtvFlexcgoSKE+pKgSx06noGR/uw3YwTK1b4b4CA+N3G++ixnlHgaBBcCW+Su8OeUOzO3dgrAFM3BreXbItBsnAla8sM+MxaXYtoz0MufSNf0FSemeT0r9kq4sA+ffgLhGQagBI7FA4RburFBxpovxRX9P8pjBsoGrdgWT3JzeDr+YOPkd6rlWQ7F/Z7/stDOVTXZx2wxw7UpHLroo29F3GizclZRuNh1CVxpZxB+dU0FFzoluVBx448D1gm0WrLZ1BfNbGHTE/Do4qYkGS4IdFYmdkB3e+fi+fKlVpCSpgm/BpPmMAwJw8we6frVCWYv/JW7SYW9n3ZEXiGWQsgScgYk+DBUpTn9k2YijPBdl+v1K0VwqB+GLgnegoRozbUxf7WgV3J4KtVfXxfZ2/TZKsGsNF9vqP7QrjfDBjWiG1UkmAEJ6RMLw="
  file: dist/sdoc-${TRAVIS_TAG}-${TARGET}.tar.gz
  skip_cleanup: true
  on:
    repo: matthewwoodruff/sdoc
    tags: true
    condition: "$TRAVIS_RUST_VERSION = stable && $TARGET != ''"
- provider: script
  script: make cargo-release
  skip_cleanup: true
  on:
    repo: matthewwoodruff/sdoc
    tags: true
    condition: "$CARGO_RELEASE = true"
