language: rust
cache: cargo
rust:
- stable
- nightly
matrix:
  fast_finish: true
  allow_failures:
  - rust: nightly
  include:
  - os: osx
    env: TARGET=x86_64-apple-darwin
  - os: linux
    env: 
    - TARGET=x86_64-unknown-linux-musl CARGO_RELEASE=true
    - secure: "XU6lsbfKQAUByYp/TIFFk/eFhktOU8x5YIBZMwy77reRcZTd8LPMJpop5zWhBhsUAW9Hz78G2Cl1xojp8KGWeNi996/PmwPaRgsfCrVrbSIn077qdqgdh+OOJwn9eBwADlkg8sy917PorRV/aEK+nPrcKPYw0rMZtVOQXT2JvRrSzfQihpnDUfdcml17Whsy/esXeP8gy4GGDyWO7AgytH8q56PEaJbejCMa2oeNtJ4nQ4nxM8qAcxMcYyNDzDdRpAHf6RxTm/FdRP1vc25mrr9qPQ2ZcHS2a+NpSlHPxgXJi45mU3UgUk8/kDfk0lNjMEUC2JamWRmZIfrtJQdj5x3/4CNbLGHrb8hapeL4NxTOaY4naNer53ea3hjheO7FMZW5gpa88GaMG0D+erMBGpvvqBzpMd5osdzWyKhd/D12okaoKuQHY7xRICmE79AHHB3+Vl6QEFyKoBo6QJ6cb5T3skUKd1r4/E/ojQcRftdf9D0z3u8eMASaqBTecgfmDm+834D/wTDcy9cyAV1k/3YY6ddXaugWCWkCZE/+3U8MLjanvCAMZPcdAshNBKS1GZotFD8qN/8D1w8yq5+xehGLA6EyidmPSqhjuht8w8fYQKjDw80QchSWC+ntx2F+881XFFQo8y/nDsHMEDRSBs0fY8KwTcO1Pi0ZMML5XfY="
  - os: linux
    env: TARGET=x86_64-unknown-linux-gnu
script: make build
deploy:
- provider: releases
  api_key:
    secure: k7Qt/VHSrEUeEo3A7+Chu3Oy1Ft5JCUyKDNIEgMA2Uz1cxSNLOBN9VH2cSGaTW01G5sMhESG2X0AaPn23cnJgy/XyXcGMs1mfWUE5/ilyhhB+Uw0w16HfHyfjTsDzwh5BnNqrmc6OjEnilLPsz0EkGe8Y9u1DP4+9iHGu6UV/rs/ZC+BJEqvWfHi+1gxVk/oF9aPVgWCviV1nKLbqtVXwVkVDpsEDNmiyHO7QFUZvwwDLL4FzcHMUaGtGKxFK+KS6JGlcUwg+/+CTpxYGpm5rXMkMCNJgIIWg+BvODvM25dpBbohEfTbOGA0ToAkFZP5XgX2E8nI/ymD/BZib8cvn0wche00+SeDVfPtQLPc6MvYiquX92ofvVz7Y68i6BJK10tZG7LzRKELuKqIdvUkUWP3S3tGyfBZNi7o7G++FcCSs3O6uGXkF/JpA1amMzpqdcHgxp+LZ5IGUtesdmOm7VIYEgpJQBzbbQxBJXIgrBm+zwHA4SpcQxrHb/XznCbQyAiTg8n4DCzyNbwIhzHOQIZqVqDSCC/Q4R25oNO08d+uJUaEFeHMXdBsEWYHQneWfkPZZQuAdx+3WH0CMkVEWnrRwsPTJ7LWOePfSLKnYhx14eg8v1ZYYioctYyxZWgQY3i+/qFlgcA6Y8ewDAVtvorHFMaBS/+Ol+J2d/xjfl8=
  file: dist/sdoc-${TRAVIS_TAG}-${TARGET}.tar.gz
  skip_cleanup: true
  on:
    repo: matthewwoodruff/sdoc
    tags: true
    condition: "$TRAVIS_RUST_VERSION = stable && $TARGET != ''"
- provider: script
  script: make cargo-release
  skip_cleanup: true
  on:
    repo: matthewwoodruff/sdoc
    condition: "$CARGO_RELEASE = true"
